name: CI

on:
  push:
    branches: [ "main" , "master", "temp"]
  pull_request:
    branches: [ "main" ]

jobs:
  ut_coverage:
    runs-on: ubuntu-24.04
    name: Unit Tests - Coverage
    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update;
        sudo apt install -y build-essential git cmake make;
        sudo apt install -y python3-pip ninja-build;
        sudo apt install -y curl zip unzip tar pkg-config;
        sudo apt install -y autoconf libtool;
        sudo apt install -y  gcovr lcov  libgtest-dev;

    - name: Config project
      run: |
        cmake -B build -S .

    - name: Build project
      run: cmake --build build -j `nproc`

    - name: Unit test with tsan
      run:  ctest --test-dir build --output-on-failure -j 2

    - name: Generate coverage file
      run: gcovr -v -r . --xml-pretty --xml=coverage.xml --exclude 'build/*' --exclude 'tests/*' --exclude 'benchmarks/*' 

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        verbose: true
