on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: coverage-data/coverage.info

    steps:
      - uses: actions/checkout@v2

      - uses: arduino/cpp-test-action@v1
        with:
          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}
          source-path: ./
          build-path: build
          runtime-paths: build/tests/test_hellocov

      # Optional: upload coverage report to codecov.io
      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.COVERAGE_DATA_PATH }}