on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: coverage-data/coverage.info

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        shell: bash
        run: |
          cmake -S . -B build
          cmake --build build

      - name: test
        shell: bash
        run: |
          cd build
          ctest --verbose

      - name: Install LCOV
        shell: bash
        run: |
          sudo apt-get --assume-yes install lcov > /dev/null

      - name: run test
        shell: bash
        run: ./build/tests/test_hellocov

      - name: Generate coverage file
        run: gcovr -v -r . --xml-pretty --xml=coverage.xml --exclude 'build/*' --exclude 'tests/*' --exclude 'benchmarks/*' --verbose

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: coverage.xml
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}